import { createSlice } from '@reduxjs/toolkit';

export const userSlice = createSlice({
  name: 'user',
  initialState: {
    user: null,
  },
 
  reducers: {
    login: (state, action) => {
      state.user = action.payload;
    }, 
    logout: (state) => {
      state.user = null;
    },
  },
});

export const { login, logout } = userSlice.actions;
//selecters
export const selectUser = (state) => state.user.user;

export default userSlice.reducer;

// Use the PayloadAction type to declare the contents of `action.payload`

// The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

//payload is an object that we pass along with it
